version: '3'

env:
  LIBRARY_DYNAMO_CONFIG_PATH: dynamo_config
  

tasks:
  init:
    cmds:
      - task: ::init-module
        vars:
          GO_MODULE_PATH: "{{.LIBRARY_DIR}}/{{.LIBRARY_DYNAMO_CONFIG_PATH}}"
      - task: :env:import
        vars:
          GO_MODULE_PATH: "{{.LIBRARY_DIR}}/{{.LIBRARY_DYNAMO_CONFIG_PATH}}"
      - cmd: go mod tidy
        silent: true
  
  import:
    cmds:
      - task: ::import-module
        vars:
          GO_MODULE_PATH: "{{.GO_MODULE_PATH}}"
          GO_LIBRARY_PATH: "{{.LIBRARY_DIR}}/{{.LIBRARY_DYNAMO_CONFIG_PATH}}"
