version: "3"

env:
  LAMBDA_ENDPOINT_CONFIG: endpoint_config
  LAMBDA_ENDPOINT_CONFIG_NAME: endpointConfig

includes:
  lambda:
    dir: ".."
    taskfile: "../Lambda.yaml"
    optional: true

tasks:
  init:
    cmds:
      - task: ::init-module
        vars:
          GO_MODULE_PATH: "{{.LAMBDA_DIR}}/{{.LAMBDA_ENDPOINT_CONFIG}}"
      - task: ::libraries:commons:import
        vars:
          GO_MODULE_PATH: "{{.LAMBDA_DIR}}/{{.LAMBDA_ENDPOINT_CONFIG}}"
      - task: ::libraries:env:import
        vars:
          GO_MODULE_PATH: "{{.LAMBDA_DIR}}/{{.LAMBDA_ENDPOINT_CONFIG}}"
      - task: ::libraries:log:import
        vars:
          GO_MODULE_PATH: "{{.LAMBDA_DIR}}/{{.LAMBDA_ENDPOINT_CONFIG}}"
      - task: ::libraries:dynamo_config:import
        vars:
          GO_MODULE_PATH: "{{.LAMBDA_DIR}}/{{.LAMBDA_ENDPOINT_CONFIG}}"
      - cmd: go mod tidy
        silent: true

  build:
    silent: true
    env:
      GOOS: linux
      GOARCH: amd64
    cmds:
      - cmd: go build -o {{.LAMBDA_BIN}}/main ./cmd
      - cmd: zip main.zip {{.LAMBDA_BIN}}/main

  logs:
    cmds:
      - task: lambda:logs
        vars:
          LAMBDA_NAME: "{{.LAMBDA_ENDPOINT_CONFIG_NAME}}"

  invoke:
    cmds:
      - task: lambda:invoke
        vars:
          LAMBDA_PATH: "{{.LAMBDA_ENDPOINT_CONFIG}}"

  start:
    cmds:
      - task: lambda:start
        vars:
          LAMBDA_PATH: "{{.LAMBDA_ENDPOINT_CONFIG}}"

  dev:
    cmds:
      - task: lambda:dev
        vars:
          LAMBDA_PATH: "{{.LAMBDA_ENDPOINT_CONFIG}}"

  update:
    cmds:
      - task: build
      - task: lambda:update
        vars:
          LAMBDA_PATH: "{{.LAMBDA_ENDPOINT_CONFIG}}"
