networks:
  aws-service:
  
services:
  aws:
    container_name: aws
    image: localstack/localstack:1.4
    environment:
      DEFAULT_REGION: ${AWS_REGION}
      TEST_AWS_ACCOUNT_ID: "000000000000"
      EXTRA_CORS_ALLOWED_ORIGINS: "*"
      PERSISTENCE: 1
      DEBUG: 1
    ports:
      - "${AWS_PORT}:4566"
    volumes:
      - ./.volume/localstack:/var/lib/localstack
      - ./aws:/etc/localstack/init/ready.d
    networks:
      - aws-service

  dynamo-gui:
    container_name: dynamo-gui
    image: aaronshaf/dynamodb-admin
    ports:
      - "${PORT}:8001"
    environment:
      DYNAMO_ENDPOINT: "http://aws:4566"
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    depends_on: ['aws']
    networks:
      - aws-service
