version: '3'

env:
  LIBRARY_ENV_PATH: env
  

tasks:
  init:
    cmds:
      - task: ::init-module
        vars:
          GO_MODULE_PATH: "{{.LIBRARY_DIR}}/{{.LIBRARY_ENV_PATH}}"
      - cmd: go mod tidy
        silent: true
  
  import:
    cmds:
      - task: ::import-module
        vars:
          GO_MODULE_PATH: "{{.GO_MODULE_PATH}}"
          GO_LIBRARY_PATH: "{{.LIBRARY_DIR}}/{{.LIBRARY_ENV_PATH}}"
